### ISSUE TITLE
Heading component voor Apache Wicket

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rotterdam#116]
- [x] Heading component direct bruikbaar als Wicket Label
- [x] Heading component met een stukje 'niet vertaalbare' tekst
- [x] Grootte van de heading op kunnen geven als parameter (h1 - h6)
- [ ] Op ComponentsPage: link naar de HTML-voorbeelden van UtrechtHeading volgens NL Design System. Waar moet dat terug te vinden zijn? In de Rotterdamse fork van het NL Design System van Utrecht (dus [hier](https://nl-design-system.github.io/rotterdam/?path=/docs/css-utrecht-heading--docs), maar daar staan nu React codevoorbeelden)?

**Comment by keesvandieren** [comment]
@Robbert  voor wat betreft naamgeving van de Wicket componenten. Wat wil je dat we aanhouden?

De namen zoals genoemd bij [componenten](https://nldesignsystem.nl/componenten/
) wil ik in ieder geval gebruiken.

Daarnaast wil ik dat ze herkenbaar zijn als zijnde van het NL Design Systeem.

Wat varianten:

* NldsHeading of UtrechtHeading of DesignSystemHeading
* NldsCodeBlock of UtrechtCodeBlock of DesignSystemCodeBlock

We kunnen de CSS class-names volgen, dan wordt het Utrecht in de meeste gevallen, aangezien die veelal gebruikt zullen worden. 

Wat heeft jouw voorkeur?

**Comment by keesvandieren** [comment]
Via Slack besloten dat het UtrechtHeading wordt (gelijk aan de CSS classname)

**Comment by keesvandieren** [comment]
PR in review bij @Robbert
