### ISSUE TITLE
Iconset in Storybook

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rotterdam#18]
- [Iconset in SVG](https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?type=design&node-id=427-11987&mode=dev)
- I know the icons are available as font and as SVG, but we need permission to publish them in this repo, even if it is without open source license. See issue #47.
- We can display the icons similar to how Utrecht does it in Storybook.

Example of Utrecht:

![nl-design-system github io_utrecht_storybook_iframe html_viewMode=docs id=utrecht-iconen--docs](https://github.com/nl-design-system/rotterdam/assets/30694/a9b03f71-9f45-43b6-b723-1089a38042ba)

**Comment by sanderdegoose** [comment]
I exported all UX icons as SVG files and included them here. I hope this does the job. These are all the UX icons from our Figma RODS

[UX icons.zip](https://github.com/nl-design-system/rotterdam/files/13588454/UX.icons.zip)
