### ISSUE TITLE
Official logo SVGs

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rotterdam#48]
@sanderdegoose Wil jij de officiële logo SVG files aanleveren?

**Comment by sanderdegoose** [comment]
Bij deze:

![Avatar](https://github.com/nl-design-system/rotterdam/assets/111966876/7ce860a9-189f-4896-94a4-58afb4c2d7a0)
![Base](https://github.com/nl-design-system/rotterdam/assets/111966876/8c0f2b31-8168-4741-9695-1ad56df32ffb)
![Mark](https://github.com/nl-design-system/rotterdam/assets/111966876/20affba0-1330-49dd-bf37-b3d5e917cb32)
![Square](https://github.com/nl-design-system/rotterdam/assets/111966876/c060dd84-029b-4729-8920-d56baf936628)
