### ISSUE TITLE
Link list component in Storybook

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/rotterdam#51]
- [Text button lists in Figma](https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?type=design&node-id=576-28738&mode=dev)
- The [link list CSS component in Utrecht](https://nl-design-system.github.io/utrecht/storybook-css/?path=/docs/css-link-list--docs) is not completely ready to as reusable white label component, but there is a work in progress pull request: nl-design-system/utrecht#2000

**Comment by bddjong** [comment]
Just did a bit more work on the utrecht PR. 

> Refactored to use utrecht icon without a marker class. Still needs a react story but ready for review after that.

**Comment by Robbert** [comment]
Done!
