### ISSUE TITLE
Navigation component in storybook

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/rotterdam#81]
- [Navigation in Figma](https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?type=design&node-id=1730-7404&mode=design&t=6y74utoKocxRPhZa-0)
- We could use tokens or CSS from the [Utrecht top navigation](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-topnav--docs)

**Comment by Robbert** [comment]
Done.
