### ISSUE TITLE
Header component in storybook

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/rotterdam#82]
Created this issue for the page element component `rotterdam-header` which will contain other components such as a logo, navigation or buttons.

- [Header in figma](https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?type=design&node-id=1730-7404&mode=design&t=6y74utoKocxRPhZa-0)
- [Den Haag header page element](https://nl-design-system.github.io/denhaag/?path=/story/css-page-elements-header--default-story)

**Comment by Robbert** [comment]
- [ ] Add border-block-end token to the Utrecht page header component  ([support is missing](https://github.com/nl-design-system/rotterdam/pull/110#discussion_r1427073106), but likely generally useful)

**Comment by Robbert** [comment]
Done as part of Mijn Loket template.
